/** Concise, user-facing summaries keyed by the campus-map object ID. */
export const campusBuildingDescriptions: Readonly<Record<string, string>> = {
  "334": "Lakeshore residence hall with student rooms and shared community spaces.",
  "335": "Home to agricultural research and outreach programs, including the Center for Integrated Agricultural Systems.",
  "336": "A campus residence associated with the College of Agricultural and Life Sciences.",
  "337": "Teaching and research in biological systems engineering.",
  "338": "Laboratories for agricultural engineering research and applied systems work.",
  "339": "The College of Agricultural and Life Sciences, with departments and research programs across agriculture and the environment.",
  "341": "Biomedical sciences teaching and graduate research.",
  "342": "Animal and dairy sciences classrooms, laboratories, and research programs.",
  "343": "Student center with cultural programs, veteran services, study-abroad support, and community spaces.",
  "344": "Research and teaching in atmospheric, oceanic, climate, and space sciences.",
  "345": "Food science and dairy research, with the Babcock Dairy Store nearby.",
  "347": "Undergraduate residence hall with student rooms and shared community spaces.",
  "348": "Campus leadership and central administration, including the Chancellor and Provost offices.",
  "350": "Offices and gathering spaces for the Wisconsin Alumni Association.",
  "351": "Biochemistry laboratories for teaching and research.",
  "352": "Biochemistry teaching and research, including biotechnology training.",
  "353": "Controlled-environment laboratories for biological research.",
  "354": "Biology and botany departments, greenhouses, imaging facilities, and the Wisconsin State Herbarium.",
  "355": "Research laboratories in biochemistry, biophysics, and cell and molecular biology.",
  "356": "Undergraduate residence hall with student rooms and shared community spaces.",
  "357": "Academic advising, student affairs, and scholarship programs for Letters & Science.",
  "358": "An 85-foot campus tower with 56 bells, played during scheduled carillon concerts.",
  "359": "Lakeshore dining market and student gathering space, with rooms for programs and events.",
  "360": "Undergraduate residence hall with student rooms and shared community spaces.",
  "361": "Physics teaching and research, plus the hands-on L.R. Ingersoll Wonders of Physics Museum.",
  "362": "A student residence house within the Kronshage Lakeshore community.",
  "363": "Chemistry department classrooms, laboratories, and the Chemistry Information Commons.",
  "364": "Major teaching hospital with emergency care, specialty clinics, and medical research.",
  "365": "Undergraduate residence hall with student rooms and shared community spaces.",
  "366": "Computer science, geography, and environmental studies programs, with computing and map-library resources.",
  "367": "Boathouse on Lake Mendota supporting UW rowing and other water-based activities.",
  "368": "Dairy barn supporting animal-science teaching and agricultural research.",
  "369": "Dairy cattle housing and facilities for teaching and research.",
  "370": "Research on dairy forage, crops, nutrition, and sustainable livestock systems.",
  "372": "School of Education classrooms and offices for teacher preparation and education programs.",
  "373": "Education research, teacher development, career support, and learning programs.",
  "374": "Lakeshore residence hall with student rooms and shared community spaces.",
  "375": "Art history programs and the Kohler Art Library, next to the Chazen Museum of Art.",
  "376": "Biomedical engineering programs and collaborative engineering design spaces.",
  "378": "Engineering classrooms and departments across the College of Engineering.",
  "379": "Engineering research in engines, nuclear science, and fusion technology.",
  "380": "Campus offices for environmental health, workplace safety, and related services.",
  "381": "Interdisciplinary research in enzymes, animal resources, and environmental sustainability.",
  "382": "Offices supporting UW Extension and educational programs serving communities across Wisconsin.",
  "383": "Indoor athletics and recreation facility with a field house and track.",
  "384": "Campus vehicle fleet, automotive repair, and service operations.",
  "385": "Executive education, conferences, meeting rooms, and guest accommodations.",
  "386": "Undergraduate residence hall with student rooms and shared community spaces.",
  "387": "Academic programs and student-support offices, including advising and teaching resources.",
  "388": "Genetics, biotechnology, and genomics research facilities.",
  "389": "Geoscience classrooms and research, with the campus Geology Museum.",
  "390": "A student residence house within the Kronshage Lakeshore community.",
  "391": "UW varsity softball fields and team facilities.",
  "392": "Aquatic-science programs, a speech and hearing clinic, and Wisconsin’s Water Library.",
  "394": "The Wisconsin School of Business, with classrooms, advising, and business programs.",
  "395": "Greenhouse space for plant growing, instruction, and research.",
  "397": "Health sciences classrooms, medical education, clinical research, and Ebling Library.",
  "398": "Campus heating and cooling plant serving nearby university buildings.",
  "400": "A university facility on Herrick Drive, near campus research and agricultural spaces.",
  "401": "State history museum, research library, archives, and collections documenting Wisconsin.",
  "402": "Horse barn for animal care, teaching, and agricultural research.",
  "403": "Horticulture teaching, plant collections, and research spaces.",
  "404": "School of Human Ecology classrooms and offices, with design galleries and textile collections.",
  "405": "Humanities and music programs, including the School of Music and Mills Concert Hall.",
  "406": "A student residence house within the Kronshage Lakeshore community.",
  "407": "Language, area-studies, and international programs, plus academic advising and student support.",
  "408": "A student residence house within the Kronshage Lakeshore community.",
  "409": "A student residence house within the Kronshage Lakeshore community.",
  "410": "Soil science and environmental research, with laboratories and academic offices.",
  "411": "Home court and ice for Badgers basketball and hockey, with major event space.",
  "412": "A student residence house within the Kronshage Lakeshore community.",
  "413": "Student housing and community space within the Kronshage residence-hall area.",
  "414": "A student residence house within the Kronshage Lakeshore community.",
  "416": "Dance and arts programs, studios, and performance spaces.",
  "417": "UW Law School classrooms, legal research centers, and the Law Library.",
  "418": "Freshwater ecology and lake research through the Center for Limnology.",
  "419": "Facilities for livestock research and animal-science teaching.",
  "420": "Conference and lodging center with meeting rooms for campus visitors and events.",
  "421": "A student residence house within the Kronshage Lakeshore community.",
  "422": "Materials science and engineering laboratories, including nanoscale research facilities.",
  "423": "Cancer research laboratories and programs at the McArdle Laboratory.",
  "426": "Research on meat science, muscle biology, and animal-derived food products.",
  "427": "Mechanical and industrial engineering classrooms, research groups, and laboratories.",
  "428": "Historic campus building that was the first dedicated home of the university medical school.",
  "429": "Medical science teaching and research, including pharmacology and clinical programs.",
  "430": "Home to Integrated Liberal Studies, an interdisciplinary undergraduate program.",
  "431": "Central campus library with study areas, archives, special collections, and music resources.",
  "432": "Lakeside student union for dining, concerts, meetings, and relaxing on the Terrace.",
  "433": "Undergraduate residence hall with student rooms and shared community spaces.",
  "434": "Student advising, orientation, transfer support, and academic technology programs.",
  "435": "Dining, meeting, and event spaces at the University Club.",
  "436": "School of Music classrooms, rehearsal rooms, and performance spaces.",
  "437": "Basketball practice courts and an adjoining plaza beside the Kohl Center.",
  "438": "Indoor tennis courts for varsity competition, lessons, and recreation.",
  "439": "Biology department classrooms, laboratories, and offices.",
  "440": "Political science classrooms and offices in one of the campus’s oldest academic buildings.",
  "441": "Nutrition science classrooms, research, and department offices.",
  "442": "Offices for the La Follette School of Public Affairs.",
  "443": "Historic astronomy observatory with a working telescope and public programs.",
  "444": "UW Police Department and campus security operations.",
  "445": "Poultry research laboratories and animal-science facilities.",
  "447": "Primate research and biomedical facilities at the Wisconsin National Primate Research Center.",
  "448": "Research laboratories for primate biology and related health sciences.",
  "449": "Psychology classrooms, research labs, and department offices.",
  "450": "Conference and meeting center, alongside international student and faculty services.",
  "451": "Radio and communication studios for campus broadcasting and media programs.",
  "452": "School of Pharmacy classrooms, laboratories, and pharmaceutical research.",
  "453": "Research and teaching in entomology, plant pathology, and forest and wildlife ecology.",
  "454": "Historic university building at Orchard Street, with campus academic and research space.",
  "455": "Sandra Rosenbaum School of Social Work classrooms and offices.",
  "456": "A covered shelter near the Lakeshore athletic fields.",
  "457": "Historic science building; access and room use may change during renovation work.",
  "459": "Undergraduate residence hall with student rooms and shared community spaces.",
  "462": "Lakeshore residence hall with student rooms and shared community spaces.",
  "463": "Soil and environmental sciences research and offices.",
  "464": "Tropical conservatory with 11 growing rooms; tours are available by appointment.",
  "465": "Life sciences communication classrooms, research, and department offices.",
  "466": "Social science departments and research in economics, sociology, anthropology, and related fields.",
  "467": "Historic academic building with classrooms and Letters & Science programs.",
  "469": "Camp Randall fitness facilities for students, staff, and Badger athletics.",
  "470": "The Badgers’ football stadium and a major venue for campus events.",
  "471": "Agriculture and life-sciences library, with university archives and research resources.",
  "472": "Astronomy, public-affairs, and gender and women’s studies programs.",
  "473": "Livestock exhibitions, animal-science programs, and campus events.",
  "474": "Wisconsin State Laboratory of Hygiene, serving public health and laboratory testing.",
  "475": "Undergraduate residence hall with student rooms and shared community spaces.",
  "476": "A student residence house within the Kronshage Lakeshore community.",
  "477": "Agricultural economics teaching and research, with cooperatives and agribusiness programs.",
  "478": "Teacher education and curriculum programs, with the Cooperative Children’s Book Center.",
  "479": "Undergraduate residence hall with student rooms and shared community spaces.",
  "480": "A student residence house within the Kronshage Lakeshore community.",
  "481": "Language and area-studies programs, humanities research, and Universities of Wisconsin offices.",
  "482": "Mathematics classrooms, research, and department offices.",
  "483": "William S. Middleton Memorial Veterans Hospital and veteran health services.",
  "484": "Veterinary school classrooms, laboratories, and clinical teaching facilities.",
  "485": "Communication arts, journalism, theatre, and public media studios and performance spaces.",
  "486": "Research and specialty clinics focused on human development, genetics, and disability services.",
  "487": "Population health research, biostatistics, and Wisconsin Alumni Research Foundation offices.",
  "488": "Research and teaching on water resources, environmental engineering, and aquatic systems.",
  "489": "Collaborative study spaces and computer-aided engineering resources.",
  "490": "College Library, English and philosophy programs, and the campus Writing Center.",
  "491": "Undergraduate residence hall with student rooms and shared community spaces.",
  "492": "Biology research and teaching labs focused on organisms, ecosystems, and biodiversity.",
  "504": "University Apartments homes for students and families, with neighborhood community spaces.",
  "505": "Student and family apartments in the Eagle Heights neighborhood.",
  "506": "Student and family apartments in the Eagle Heights neighborhood.",
  "507": "Student and family apartments in the Eagle Heights neighborhood.",
  "508": "Student and family apartments in the Eagle Heights neighborhood.",
  "509": "Student and family apartments in the Eagle Heights neighborhood.",
  "510": "Student and family apartments in the Eagle Heights neighborhood.",
  "511": "Student and family apartments in the Eagle Heights neighborhood.",
  "512": "Student and family apartments in the Eagle Heights neighborhood.",
  "513": "A university facility on University Bay Drive near the Lakeshore Preserve.",
  "514": "Medical science teaching, laboratories, and health research facilities.",
  "515": "Medical laboratories supporting biomedical research and health-sciences programs.",
  "516": "Research on cereal crops, plant genetics, and agricultural production.",
  "517": "Soil-science greenhouse supporting plant research and agricultural instruction.",
  "519": "Student career services and communication offices near State Street.",
  "520": "Humanities centers and research programs in languages, culture, and history.",
  "521": "Studios and workspaces for visual arts students and faculty.",
  "522": "A university campus facility on Bernard Court, near East Campus Mall.",
  "523": "Former home of Gender and Women’s Studies, with a place in the history of that campus program.",
  "524": "Indigenous Student Center, with space for community, cultural programs, and student support.",
  "525": "Student services, health and counseling support, financial aid, and student radio.",
  "528": "Primate research support facility near the Capitol Court campus area.",
  "530": "Administrative offices for UW Intercollegiate Athletics near Camp Randall Stadium.",
  "531": "Agronomy and agroecology teaching, research, and field-science programs.",
  "532": "Plant sciences classrooms, laboratories, and research programs.",
  "534": "Undergraduate residence hall with student rooms, dining, and community spaces.",
  "535": "Naval ROTC classrooms and offices.",
  "536": "A university facility on University Avenue near the central campus.",
  "537": "Headquarters for the Wisconsin Foundation and Alumni Association.",
  "538": "Army ROTC classrooms and offices.",
  "539": "Forest products research on wood, materials, and sustainable manufacturing.",
  "540": "Campus energy plant that generates electricity and provides heating and cooling.",
  "545": "Facilities Planning and Management offices, including employee support services.",
  "546": "Undergraduate residence hall with student rooms and shared community spaces.",
  "547": "Veterinary diagnostic laboratory serving animal health and disease testing.",
  "548": "Campus administration and support offices, including safety, facilities, and human resources.",
  "549": "Air Force ROTC classrooms and offices.",
  "550": "Undergraduate residence hall with student rooms and shared community spaces.",
  "551": "Research and teaching in bacteriology, food science, and medical microbiology.",
  "618": "Medical research center with laboratories for cardiovascular, eye, cancer, and neuroscience research.",
  "641": "A group of undergraduate residence halls in the Southeast campus neighborhood.",
  "642": "University Apartments homes for students and families in the Eagle Heights neighborhood.",
  "644": "Children’s hospital providing pediatric care, specialty clinics, and family support.",
  "647": "Student union with dining, a cinema, bowling, and campus and visitor services.",
  "648": "Public-facing research building with the Wisconsin Institute for Discovery and a community Town Center.",
  "649": "Admissions and McBurney Disability Resource Center services, with student programs.",
  "650": "Free-admission art museum with galleries spanning ancient, modern, and contemporary work.",
  "651": "Home ice for Badgers women’s hockey and other campus events.",
  "652": "Research and collaboration on energy, bioenergy, and clean-energy technology.",
  "654": "Medical clinics and specialty-care offices affiliated with UW Health and the medical school.",
  "660": "Biochemistry research laboratories and academic programs.",
  "662": "Offices and support facilities for UW Intercollegiate Athletics.",
  "669": "Campus dining, meeting, and event spaces serving the Southeast residence-hall area.",
  "672": "Lakeshore residence hall with student rooms and shared community spaces.",
  "689": "School of Nursing classrooms, simulation labs, and clinical training spaces.",
  "690": "Eagle Heights community hub with child care, a gym, study rooms, and resident services.",
  "691": "Furnished apartments for UW–Madison graduate students.",
  "692": "Child-care center for children of UW–Madison students, faculty, and staff.",
  "694": "Lakeshore residence hall made up of smaller student residence houses.",
  "697": "Physical Plant offices and campus facilities-support operations.",
  "700": "Resident services and facilities office for University Apartments.",
  "701": "Music performance venue with rehearsal, teaching, and concert spaces.",
  "703": "Research and discovery in meat science, animal biologics, and food production.",
  "704": "Meeting and event venue for alumni and university groups.",
  "713": "Campus recreation center with fitness, courts, climbing, and wellness programs.",
  "714": "Campus heating and cooling plant serving nearby university buildings.",
  "719": "Laboratories studying microbes and food safety in meat and animal products.",
  "721": "Veterinary medicine teaching, research, and clinical facilities.",
  "722": "Recreation and wellbeing center with fitness, a pool, courts, climbing, and wellness services.",
  "729": "College of Computing, Data & AI classrooms, research, and library resources.",
  "731": "Indoor arena used for ice sports and athletic training.",
  "734": "Dining marketplace with multiple stations and spaces to eat or study.",
  "738": "Statewide education, agriculture, community development, and outreach programs.",
  "739": "Office of Student Conduct and Community Standards.",
  "740": "Home for humanities and qualitative social-science departments and research centers.",
  "742": "Wisconsin Entrepreneurship Hub, supporting startup learning and business innovation.",
};
